### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by whz945565** [smn2010/FGC-PR#1]
![image](https://user-images.githubusercontent.com/73058445/150387187-b83a7a56-ff2c-4697-8548-713c4a4efbe3.jpeg)

Which one should I run if I only want to use this article method

**Comment by smn2010** [comment]
The first one will do. However, the current released codes need revisions. Detailed instruction will come soon.

**Comment by whz945565** [comment]
Great work, I would like to use my own set threshold strategy, combined with your knn method.  Looking forward to your perfect code
