### ISSUE TITLE
inconsistent results

### ISSUE THREAD

**Issue by whz945565** [smn2010/FGC-PR#2]
I used the settings of the article to train cifar10 on resnet20. I set kappa to 0.03, nn_num to 200, and rho to 0.4. The remaining specific parameters are as follows, but the pruning rate after training is only more than 30%, while  It's not more than 50%, is my other parameter settings wrong?  I wonder if it's because of L0_START and L0_END![image](https://user-images.githubusercontent.com/73058445/150911544-b18ad620-bc6d-4a82-82da-8c1721b7e8a6.jpeg)

**Comment by smn2010** [comment]
Please try the uploaded codes for CIFAR10.  Let me know if you have any questions.

**Comment by whz945565** [comment]
> Please try the uploaded codes for CIFAR10.  Let me know if you have any questions.

Thank you, I ran the latest code, but after use, the memory occupancy has been above 90%, the program num_worker is 4, prompted me that the memory cannot release, which had to drive me to set num_worker to 0. I think the program may have a memory leakage problem is not handled, what should be done next
